<?php

use App\Pekerjaan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PekerjaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Pekerjaan::truncate();
        Pekerjaan::create(['nama' => 'Belum/Tidak Berja']);
        Pekerjaan::create(['nama' => 'Mengurus Rumah Tangga']);
        Pekerjaan::create(['nama' => 'Pelajar/Mahasiswa']);
        Pekerjaan::create(['nama' => 'Purnawirawan/Pensiun']);
        Pekerjaan::create(['nama' => 'Pegawai Negeri Sipil (PNS)']);
        Pekerjaan::create(['nama' => 'Tentara Nasional Indonesia (TNI)']);
        Pekerjaan::create(['nama' => 'Kepolisian RI (POLRI)']);
        Pekerjaan::create(['nama' => 'Perdagangan']);
        Pekerjaan::create(['nama' => 'Petani/Pekebun']);
        Pekerjaan::create(['nama' => 'Peternak']);
        Pekerjaan::create(['nama' => 'Nelayan/Perikanan']);
        Pekerjaan::create(['nama' => 'Industri']);
        Pekerjaan::create(['nama' => 'Konstruksi']);
        Pekerjaan::create(['nama' => 'Transportasi']);
        Pekerjaan::create(['nama' => 'Karyawan Swasta']);
        Pekerjaan::create(['nama' => 'Karyawan BUMN']);
        Pekerjaan::create(['nama' => 'Karyawan BUMD']);
        Pekerjaan::create(['nama' => 'Karyawan Honorer']);
        Pekerjaan::create(['nama' => 'Buruh Harian Lepas']);
        Pekerjaan::create(['nama' => 'Buruh Tani/Perkebunan']);
        Pekerjaan::create(['nama' => 'Buruh Nelayan/Perikanan']);
        Pekerjaan::create(['nama' => 'Buruh Peternakan']);
        Pekerjaan::create(['nama' => 'Pembantu rumah tangga']);
        Pekerjaan::create(['nama' => 'Tukang Cukur']);
        Pekerjaan::create(['nama' => 'Tukang Listrik']);
        Pekerjaan::create(['nama' => 'Tukang Batu']);
        Pekerjaan::create(['nama' => 'Tukang Kayu']);
        Pekerjaan::create(['nama' => 'Tukang Sol Sepatu']);
        Pekerjaan::create(['nama' => 'Tukang Las/Pandai Besi']);
        Pekerjaan::create(['nama' => 'Tukang Jahit']);
        Pekerjaan::create(['nama' => 'Tukang Gigi']);
        Pekerjaan::create(['nama' => 'Penata Rias']);
        Pekerjaan::create(['nama' => 'Penata Busana']);
        Pekerjaan::create(['nama' => 'Penata Rambut']);
        Pekerjaan::create(['nama' => 'Mekanik']);
        Pekerjaan::create(['nama' => 'Seniman/Artis']);
        Pekerjaan::create(['nama' => 'Tabib']);
        Pekerjaan::create(['nama' => 'Paraji']);
        Pekerjaan::create(['nama' => 'Perancang Busana']);
        Pekerjaan::create(['nama' => 'Penterjemah']);
        Pekerjaan::create(['nama' => 'Imam Masjid']);
        Pekerjaan::create(['nama' => 'Pendeta']);
        Pekerjaan::create(['nama' => 'Pastor']);
        Pekerjaan::create(['nama' => 'Wartawan']);
        Pekerjaan::create(['nama' => 'Ustadz/Mubaligh']);
        Pekerjaan::create(['nama' => 'Juru Masak']);
        Pekerjaan::create(['nama' => 'Promotor Acara']);
        Pekerjaan::create(['nama' => 'Anggota DPR-RI']);
        Pekerjaan::create(['nama' => 'Anggota DPD']);
        Pekerjaan::create(['nama' => 'Anggota KPK']);
        Pekerjaan::create(['nama' => 'Presiden']);
        Pekerjaan::create(['nama' => 'Wakil presiden']);
        Pekerjaan::create(['nama' => 'Anggota Mahkamah Konstitusi']);
        Pekerjaan::create(['nama' => 'Anggota Kabinet Kementrian']);
        Pekerjaan::create(['nama' => 'Duta Besar']);
        Pekerjaan::create(['nama' => 'Gubernur']);
        Pekerjaan::create(['nama' => 'Wakil Gubernur']);
        Pekerjaan::create(['nama' => 'Bupati']);
        Pekerjaan::create(['nama' => 'Wakil bupati']);
        Pekerjaan::create(['nama' => 'Walikota']);
        Pekerjaan::create(['nama' => 'Wakil Walikota']);
        Pekerjaan::create(['nama' => 'Anggota DPRD Provinsi']);
        Pekerjaan::create(['nama' => 'Anggota DPRD Kabupaten/Kota']);
        Pekerjaan::create(['nama' => 'Dosen']);
        Pekerjaan::create(['nama' => 'Guru']);
        Pekerjaan::create(['nama' => 'Pilot']);
        Pekerjaan::create(['nama' => 'Pengacara']);
        Pekerjaan::create(['nama' => 'Notaris']);
        Pekerjaan::create(['nama' => 'Arsitektur/Desainer']);
        Pekerjaan::create(['nama' => 'Akuntan']);
        Pekerjaan::create(['nama' => 'Konsultan']);
        Pekerjaan::create(['nama' => 'Dokter']);
        Pekerjaan::create(['nama' => 'Bidan']);
        Pekerjaan::create(['nama' => 'Perawat']);
        Pekerjaan::create(['nama' => 'Apoteker']);
        Pekerjaan::create(['nama' => 'Psikiater/Psikolog']);
        Pekerjaan::create(['nama' => 'Penyiar Televisi']);
        Pekerjaan::create(['nama' => 'Penyiar Radio']);
        Pekerjaan::create(['nama' => 'Pelaut']);
        Pekerjaan::create(['nama' => 'peneliti']);
        Pekerjaan::create(['nama' => 'Sopir']);
        Pekerjaan::create(['nama' => 'Pialang']);
        Pekerjaan::create(['nama' => 'Dukun/Paranormal/Supranatural']);
        Pekerjaan::create(['nama' => 'Pedagang']);
        Pekerjaan::create(['nama' => 'Perangkat Desa']);
        Pekerjaan::create(['nama' => 'Kepala Desa']);
        Pekerjaan::create(['nama' => 'Biarawati']);
        Pekerjaan::create(['nama' => 'Wiraswasta']);
        Pekerjaan::create(['nama' => 'Lainnya']);
        Pekerjaan::create(['nama' => 'Ahli Pengobatan Alternatif']);
        Pekerjaan::create(['nama' => 'Anggota Legislatif']);
        Pekerjaan::create(['nama' => 'Belum Bekerja']);
        Pekerjaan::create(['nama' => 'Bidan Swasta']);
        Pekerjaan::create(['nama' => 'Buruh jasa perdagangan hasil bumi']);
        Pekerjaan::create(['nama' => 'Buruh Migran']);
        Pekerjaan::create(['nama' => 'Buruh usaha hotel dan penginapan lainnya']);
        Pekerjaan::create(['nama' => 'Buruh usaha jasa hiburan dan pariwisata']);
        Pekerjaan::create(['nama' => 'Buruh usaha jasa informasi dan komunikasi']);
        Pekerjaan::create(['nama' => 'Buruh usaha jasa transportasi dan perhubungan']);
        Pekerjaan::create(['nama' => 'Dokter swasta']);
        Pekerjaan::create(['nama' => 'Dosen swasta']);
        Pekerjaan::create(['nama' => 'Dukun Tradisional']);
        Pekerjaan::create(['nama' => 'Guru swasta']);
        Pekerjaan::create(['nama' => 'Ibu Rumah Tangga']);
        Pekerjaan::create(['nama' => 'Jasa Konsultansi Manajemen dan Teknis']);
        Pekerjaan::create(['nama' => 'Jasa pengobatan alternatif']);
        Pekerjaan::create(['nama' => 'Jasa penyewaan peralatan pesta']);
        Pekerjaan::create(['nama' => 'Karyawan Perusahaan Pemerintah']);
        Pekerjaan::create(['nama' => 'Karyawan Perusahaan Swasta']);
        Pekerjaan::create(['nama' => 'Kepala Daerah']);
        Pekerjaan::create(['nama' => 'Konsultan Manajemen dan Teknis']);
        Pekerjaan::create(['nama' => 'Kontraktor']);
        Pekerjaan::create(['nama' => 'Montir']);
        Pekerjaan::create(['nama' => 'Pedagang barang kelontong']);
        Pekerjaan::create(['nama' => 'Pedagang Keliling']);
        Pekerjaan::create(['nama' => 'Pemilik perusahaan']);
        Pekerjaan::create(['nama' => 'Pemilik usaha hotel dan penginapan lainnya']);
        Pekerjaan::create(['nama' => 'Pemilik usaha informasi dan komunikasi']);
        Pekerjaan::create(['nama' => 'Pemilik usaha jasa hiburan dan pariwisata']);
        Pekerjaan::create(['nama' => 'Pemilik usaha jasa transportasi dan perhubungan']);
        Pekerjaan::create(['nama' => 'Pemilik usaha warung, rumah makan dan restoran']);
        Pekerjaan::create(['nama' => 'Pemuka Agama']);
        Pekerjaan::create(['nama' => 'Pemulung']);
        Pekerjaan::create(['nama' => 'Penambang']);
        Pekerjaan::create(['nama' => 'Pengrajin']);
        Pekerjaan::create(['nama' => 'Pengrajin industri rumah tangga lainnya']);
        Pekerjaan::create(['nama' => 'Pengusaha kecil, menengah dan besar']);
        Pekerjaan::create(['nama' => 'Pengusaha perdagangan hasil bumi']);
        Pekerjaan::create(['nama' => 'Perawat swasta']);
        Pekerjaan::create(['nama' => 'Satpam/Security']);
        Pekerjaan::create(['nama' => 'Tidak Mempunyai Pekerjaan Tetap']);
        Pekerjaan::create(['nama' => 'Tukang Anyaman']);
        Pekerjaan::create(['nama' => 'Tukang Cuci']);
        Pekerjaan::create(['nama' => 'Tukang Kue']);
        Pekerjaan::create(['nama' => 'Tukang Sumur']);
        Pekerjaan::create(['nama' => 'Usaha jasa pengerah tenaga kerja']);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
